const cssFiles = {
    "sunny": "styles/sunny.css",
    "clear": "styles/sunny.css",
    "partly cloudy": "styles/cloudy.css",
    "cloudy": "styles/cloudy.css",
    "overcast": "styles/cloudy.css",
    "mist": "styles/mist.css",
    "fog": "styles/mist.css",
    "freezing fog": "styles/mist.css",
    "thunderstorm": "styles/thunderstorm.css",
    "thundery outbreaks possible": "styles/thunderstorm.css",
    "patchy light rain with thunder": "styles/thunderstorm.css",
    "moderate or heavy rain with thunder": "styles/thunderstorm.css",
    "patchy light snow with thunder": "styles/thunderstorm.css",
    "modern or heavy snow with thunder": "styles/thunderstorm.css",
    "rain": "styles/rain.css",
    "patchy rain possible": "styles/rain.css",
    "patchy freezing drizzle possible": "styles/rain.css",
    "patchy light drizzle": "styles/rain.css",
    "light drizzle": "styles/rain.css",
    "freezing drizzle": "styles/rain.css",
    "heavy freezing drizzle": "styles/rain.css",
    "patchy light rain": "styles/rain.css",
    "light rain": "styles/rain.css",
    "moderate rain at times": "styles/rain.css",
    "moderate rain": "styles/rain.css",
    "heavy rain at times": "styles/rain.css",
    "heavy rain": "styles/rain.css",
    "light freezing rain": "styles/rain.css",
    "light rain shower": "styles/rain.css",
    "moderate or heavy rain shower": "styles/rain.css",
    "torrential rain shower": "styles/rain.css",
    "light sleet showers": "styles/rain.css",
    "moderate or heavy sleet showers": "styles/rain.css",
    "moderate or heavy freezing rain": "styles/rain.css",
    "light sleet": "styles/snow.css",
    "moderate or heavy sleet": "styles/snow.css",
    "patchy light snow": "styles/snow.css",
    "light snow": "styles/snow.css",
    "light snow showers": "styles/snow.css",
    "moderate or heavy snow showers": "styles/snow.css",
    "light showers of ice pellets": "styles/snow.css",
    "patchy moderate snow": "styles/snow.css",
    "moderate snow": "styles/snow.css",
    "patchy heavy snow": "styles/snow.css",
    "heavy snow": "styles/snow.css",
    "ice pellets": "styles/snow.css",
    "patchy snow possible": "styles/snow.css",
    "blizzard": "styles/snow.css",
    "blowing snow": "styles/snow.css",
    "snow": "styles/snow.css",
    "patchy sleet possible": "styles/snow.css",
    "default": "styles/def.css"
  };
